export const styles = `
.tt-game{--tt-ice:#c1f6ff;--tt-orange:#ffb574;position:relative;isolation:isolate;width:100%;height:100%;min-height:260px;overflow:hidden;background:#07151d;color:#f1f9fc;font-family:Inter,"Segoe UI","PingFang SC","Microsoft YaHei",sans-serif;font-size:14px;color-scheme:dark}
.tt-game *{box-sizing:border-box}.tt-game button,.tt-game select{font:inherit}.tt-game button{cursor:pointer}.tt-game button:focus-visible,.tt-game canvas:focus-visible{outline:2px solid var(--tt-ice);outline-offset:3px}.tt-game button:disabled{opacity:.45;cursor:default}
.tt-canvas{display:block;width:100%;height:100%;outline:0;touch-action:none}
.tt-top{position:absolute;top:max(10px,env(safe-area-inset-top));left:max(12px,env(safe-area-inset-left));right:max(12px,env(safe-area-inset-right));display:grid;grid-template-columns:minmax(90px,1fr) auto minmax(90px,1fr);gap:16px;align-items:start;pointer-events:none}
.tt-top button,.tt-top select{pointer-events:auto}.tt-brand{font-size:10px;letter-spacing:.19em;text-transform:uppercase;color:#c3d7df;margin:8px 0 5px}.tt-side{display:flex;gap:8px;align-items:center}.tt-side--end{justify-content:flex-end}
.tt-icon,.tt-text-button{min-width:44px;min-height:44px;border:1px solid #d6f5ff2b;background:#06121f75;color:#f4fbff;border-radius:13px;backdrop-filter:blur(10px);padding:0 12px;transition:background .16s}.tt-icon:hover,.tt-text-button:hover{background:#16364585}.tt-icon{font-size:20px;padding:0 9px}.tt-icon svg{width:20px;height:20px;vertical-align:middle;fill:none;stroke:currentColor;stroke-width:1.7}
.tt-scoreboard{display:grid;grid-template-columns:minmax(56px,130px) auto minmax(56px,130px);align-items:center;gap:18px;text-align:center;padding:9px 20px 8px;border:1px solid #d6f5ff26;border-radius:18px;background:#06121f80;backdrop-filter:blur(12px);text-shadow:0 1px 6px #0008}.tt-player{overflow:hidden}.tt-player-name{font-size:12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;color:#e4f1f5}.tt-player-games{font-size:10px;color:#c3dce6;margin-top:3px}.tt-points{font-size:31px;font-weight:700;letter-spacing:.035em;line-height:1.02;white-space:nowrap}.tt-points b:first-child{color:#a9f4ff}.tt-points b:last-child{color:#ffbd89}.tt-points span{padding:0 12px;color:#b5c7cc66;font-weight:300}.tt-match-detail{margin-top:5px;font-size:10px;letter-spacing:.04em;color:#c7dce6}.tt-serving::before{content:"";display:inline-block;width:5px;height:5px;border-radius:50%;background:var(--tt-orange);margin-right:5px;vertical-align:middle}
.tt-status{position:absolute;bottom:max(22px,env(safe-area-inset-bottom));left:max(22px,env(safe-area-inset-left));max-width:min(58%,370px);pointer-events:none;text-shadow:0 2px 8px #001019}.tt-status-label{font-size:10px;letter-spacing:.13em;text-transform:uppercase;color:#a7d9e5;margin-bottom:6px}.tt-status-main{font-weight:600;font-size:17px;line-height:1.45}.tt-status-help{font-size:11px;color:#c8dce3;margin-top:5px;line-height:1.5}
.tt-actions{position:absolute;bottom:max(18px,env(safe-area-inset-bottom));right:max(18px,env(safe-area-inset-right));display:flex;align-items:center;gap:9px}.tt-primary{border:1px solid #ffe2c177;color:#24180d;background:#ffc186;min-height:48px;min-width:120px;border-radius:15px;padding:10px 18px;font-weight:700;box-shadow:0 4px 25px #0002}.tt-primary:active{background:#ffad61}.tt-primary[hidden],.tt-game [hidden]{display:none!important}
.tt-swipe-meter{position:absolute;left:50%;bottom:max(28px,env(safe-area-inset-bottom));transform:translateX(-50%);width:112px;opacity:0;transition:opacity .12s;pointer-events:none}.tt-swipe-meter[data-active="true"]{opacity:1}.tt-meter-track{height:3px;border-radius:3px;background:#b8eaff38;overflow:hidden}.tt-meter-fill{height:100%;width:0;background:var(--tt-orange)}.tt-meter-label{font-size:10px;text-align:center;letter-spacing:.1em;color:#ffe2c4;margin-top:7px}
.tt-modal{position:absolute;inset:0;display:grid;place-items:center;padding:20px;background:#020c17a6;backdrop-filter:blur(8px);z-index:4}.tt-panel{max-width:440px;width:100%;border:1px solid #d0edf438;border-radius:22px;padding:30px;background:#101f2bf0;box-shadow:0 20px 90px #0007}.tt-kicker{font-size:10px;letter-spacing:.17em;text-transform:uppercase;color:#9ce8fa}.tt-panel h2{font-size:27px;font-weight:600;margin:12px 0;letter-spacing:-.03em}.tt-panel p{line-height:1.8;color:#bcd0d9;margin:0 0 22px}.tt-panel-actions{display:flex;gap:10px;flex-wrap:wrap}.tt-panel .tt-primary{flex:1}.tt-panel .tt-text-button{flex:1;min-height:48px}.tt-loading-line{height:3px;background:#b8eaff23;margin:20px 0;border-radius:3px;overflow:hidden}.tt-loading-line::after{content:"";display:block;height:100%;width:35%;background:#b2f3ff;animation:tt-loading 1.6s ease-in-out infinite}.tt-result-score{font-size:48px;letter-spacing:.07em;color:#c7f7ff;margin:20px 0}.tt-latency{font-size:10px;color:#c4d8df;white-space:nowrap}.tt-rotate{display:none}
@keyframes tt-loading{0%{transform:translateX(-120%)}100%{transform:translateX(400%)}}
@media(max-width:700px){.tt-top{gap:5px;grid-template-columns:48px minmax(0,1fr) 48px}.tt-brand,.tt-latency{display:none}.tt-side .tt-text-button{display:none}.tt-scoreboard{padding:8px 10px;gap:8px;border-radius:15px;grid-template-columns:minmax(40px,1fr) auto minmax(40px,1fr)}.tt-points{font-size:27px}.tt-points span{padding:0 6px}.tt-player-name{font-size:11px}.tt-status{left:max(14px,env(safe-area-inset-left));bottom:max(17px,env(safe-area-inset-bottom));max-width:58%}.tt-status-main{font-size:14px}.tt-status-label{font-size:9px}.tt-status-help{font-size:10px}.tt-actions{right:max(12px,env(safe-area-inset-right));bottom:max(14px,env(safe-area-inset-bottom))}.tt-primary{min-width:105px;min-height:46px;padding:10px 13px}.tt-panel{padding:24px}.tt-panel h2{font-size:24px}}
@media(max-height:450px){.tt-top{top:max(6px,env(safe-area-inset-top))}.tt-scoreboard{padding-top:5px;padding-bottom:5px}.tt-brand{display:none}.tt-points{font-size:26px}.tt-match-detail{margin-top:3px}.tt-status-help{display:none}.tt-status{bottom:max(12px,env(safe-area-inset-bottom))}.tt-actions{bottom:max(10px,env(safe-area-inset-bottom))}.tt-panel{padding:20px;max-width:460px}.tt-panel h2{font-size:22px;margin:8px 0}.tt-panel p{font-size:12px;margin-bottom:15px}.tt-result-score{font-size:36px;margin:10px 0}}
@media(orientation:portrait) and (max-width:600px){.tt-status{bottom:max(26px,env(safe-area-inset-bottom))}.tt-status-help{max-width:180px}.tt-rotate{display:block;position:absolute;top:92px;left:50%;transform:translateX(-50%);font-size:10px;color:#ddedf3;white-space:nowrap;pointer-events:none;text-shadow:0 2px 7px #000}.tt-swipe-meter{bottom:105px}}
/* Game geometry stays untouched beneath the shared scene-sampled glass. */
.tt-canvas{position:absolute;inset:0;z-index:0}.tt-game>.caesar-optical-layer{z-index:1}.tt-top,.tt-status,.tt-actions,.tt-controls,.tt-guide,.tt-swipe-meter,.tt-rotate{z-index:2}
.tt-game{color:var(--glass-ink,#eff8ff)}.tt-scoreboard,.tt-controls{background:var(--glass-tint);color:var(--glass-ink);border-color:var(--glass-rim);box-shadow:var(--glass-shadow);text-shadow:none;backdrop-filter:blur(4px)}.tt-scoreboard[data-optical-ready=true],.tt-controls[data-optical-ready=true]{backdrop-filter:none}
.tt-game .tt-player-name,.tt-game .tt-points b{color:var(--glass-ink)}.tt-player-games,.tt-match-detail{color:var(--glass-muted)}.tt-points span{color:var(--glass-muted);opacity:.65}.tt-icon,.tt-text-button{color:var(--glass-ink);background:var(--glass-tint);border-color:var(--glass-rim);backdrop-filter:blur(4px)}.tt-icon:hover,.tt-text-button:hover{background:var(--glass-tint)}
.tt-status{bottom:calc(max(18px,env(safe-area-inset-bottom)) + 58px);max-width:min(62%,390px);color:#f4fbff;text-shadow:0 1px 3px #07151d,0 1px 10px #07151d}.tt-status-label{display:none}.tt-status-main{font-size:13px}.tt-status-help{font-size:10px}.tt-brand,.tt-latency{color:#f1f9fc;text-shadow:0 1px 4px #081a29}
.tt-controls{position:absolute;left:max(14px,env(safe-area-inset-left));bottom:max(14px,env(safe-area-inset-bottom));width:min(350px,calc(100% - 144px));border:1px solid var(--glass-rim);border-radius:15px;padding:4px}.tt-techniques{display:flex;gap:3px}.tt-techniques button{flex:1;min-width:0;min-height:40px;border:0;border-radius:10px;background:transparent;color:var(--glass-ink);font-size:12px;padding:3px;white-space:nowrap}.tt-techniques button[aria-pressed=true]{background:color-mix(in srgb,var(--glass-accent) 20%,transparent);box-shadow:inset 0 0 0 1px var(--glass-rim);font-weight:700}.tt-techniques .tt-adjust{color:var(--glass-muted);font-size:11px}.tt-stroke-settings{position:absolute;bottom:calc(100% + 7px);left:0;width:min(310px,100%);border:1px solid var(--glass-rim);border-radius:16px;background:var(--glass-tint);color:var(--glass-ink);backdrop-filter:blur(18px);padding:12px}.tt-stroke-settings label{display:grid;grid-template-columns:1fr auto;align-items:center;gap:3px;font-size:11px;margin-top:8px}.tt-stroke-settings input{grid-column:1/-1;width:100%;height:24px;accent-color:var(--glass-accent);touch-action:pan-x;margin:0}.tt-stroke-settings output{font-variant-numeric:tabular-nums}.tt-stroke-settings small{font-size:10px;color:var(--glass-muted)}.tt-technique-help{font-size:11px;margin:0 0 6px}.tt-controls:has(.tt-stroke-settings:not([hidden]))~.tt-guide{display:none}
.tt-guide{position:absolute;left:max(14px,env(safe-area-inset-left));top:90px;max-width:min(340px,calc(100% - 28px));padding:9px 12px;border-radius:13px;font-size:11px;line-height:1.6;display:flex;gap:8px;align-items:center}.tt-guide-skip{flex:none;min-height:36px;border:0;background:transparent;color:var(--glass-accent);font-size:11px;padding:2px}.tt-swipe-meter{bottom:90px}.tt-actions .tt-primary{min-width:110px}.tt-primary{background:var(--glass-accent,#87dae4);border-color:var(--glass-rim);color:#fff}.tt-panel{color:var(--glass-ink);background:var(--glass-tint);border-color:var(--glass-rim);backdrop-filter:blur(18px)}.tt-panel p{color:var(--glass-muted)}.tt-kicker,.tt-result-score{color:var(--glass-accent)}.tt-modal{background:#07121c45;backdrop-filter:blur(6px)}
@media(max-height:450px){.tt-status{bottom:calc(max(10px,env(safe-area-inset-bottom)) + 53px)}.tt-controls{bottom:max(8px,env(safe-area-inset-bottom));width:300px}.tt-techniques button{min-height:36px}.tt-guide{top:74px;max-width:300px;padding:5px 10px}.tt-stroke-settings{padding:8px}.tt-stroke-settings label{margin-top:2px}.tt-stroke-settings small{display:none}}
@media(orientation:portrait) and (max-width:600px){.tt-controls{width:calc(100% - 28px);bottom:max(14px,env(safe-area-inset-bottom))}.tt-actions{bottom:calc(max(14px,env(safe-area-inset-bottom)) + 62px)}.tt-status{bottom:calc(max(14px,env(safe-area-inset-bottom)) + 61px);max-width:calc(100% - 155px)}.tt-status-help{display:none}.tt-guide{top:114px}.tt-swipe-meter{bottom:142px}.tt-rotate{top:92px}}
.tt-game[data-glass-theme="dark"] .tt-primary{color:#102630}
/* A venue is not a light/dark page: keep match labels readable over either wall. */
.tt-game[data-glass-theme]{--glass-ink:#f0f8fc;--glass-muted:#d1e3ed;--glass-tint:rgb(8 24 36 / 24%)}
.tt-scoreboard,.tt-guide,.tt-controls,.tt-icon,.tt-text-button{text-shadow:0 1px 3px #07151d99}
.tt-guide-skip{color:var(--glass-ink)}
@media(prefers-reduced-motion:reduce){.tt-game *{animation:none!important;transition:none!important}}
`
